### ISSUE TITLE
Problème lors du chargement de fichier

### ISSUE THREAD

**Issue by Yxshad** [RomLabo/JustAlgoIt#1]
[romlabo.github.io-1696843485639.log](https://github.com/RomLabo/JustAlgoIt/files/12844404/romlabo.github.io-1696843485639.log)

Je mettrai un meilleur log car là c'est que les erreurs. J'ai eu des soucis pour ouvrir un fichier png IrfanView. Soit l'écran clignotait soit ça plantait sans l'ouvrir mais voilà.

**Comment by RomLabo** [comment]
Le problème vient d'une différence entre la taille de l'image que tu charges et la taille du canvas de l'application, je viens de corriger le problème. Maintenant il est possible d'enregistrer ton algo depuis un grand écran et l'ouvrir sur un écran plus petit et vice-versa, sans problème, cependant je n'ai pas encore réglé le problème de la taille de la police en fonction de la taille d'écran, donc sur un petit écran les noeuds peuvent se superposés. 
Merci de m'avoir signaler le bug.
